### ISSUE TITLE
Merge with httpie

### ISSUE THREAD

**Issue by Yamakaky** [reorx/httpstat#10]
Cool program! Did you consider merging with [httpie](https://httpie.org/), maybe behind a cli flag?

**Comment by reorx** [comment]
Actually, I intended to do so at the beginning, but then I changed my mind
after looking around the code base of httpie. Httpie uses requests to
handle HTTP things, in order to get time stats, you have to intercept into
requests and count time in every phase of the requesting process, that
makes it a feature request of both requests library and httpie, it's the
ideal way but it takes much much time and depends a lot on authors'
attitudes. So I just choose the simplest way, leverage the power of curl,
and make it work.

I like requests and httpie a lot (the ui of httpstat imitates httpie's
somewhat) and hope to see time statistics as part of their functionalities
some day, that time httpstat is happy to be an alternative.
Yamakaky <notifications@github.com>于2016年9月26日 周一上午6:46写道：

**Comment by Yamakaky** [comment]
Ok, cool. And yeah, I noticed the similarity in the interfaces ^^
