### ISSUE TITLE
Error when running on Linux/Python 2.6

### ISSUE THREAD

**Issue by GClover1985** [reorx/httpstat#23]
python httpstat.py httpbin.org/get
  File "httpstat.py", line 110
    grayscale = {(i - 232): make_color('38;5;' + str(i)) for i in xrange(232, 256)}
                                                           ^
SyntaxError: invalid syntax

Redhat 6.5, Python 2.6

**Comment by GClover1985** [comment]
![image](https://cloud.githubusercontent.com/assets/6895607/19718375/a19a0eae-9b97-11e6-8238-3e36e84b3d02.png)

**Comment by reorx** [comment]
Sorry for the late response. This is caused by your Python version, the dict comprehension `{k:v for k in xxx}` syntax is not supported by Python 2.6. I can just change this to another way but there are still a large number of 2.6 incompatible code in this project, I don't have that much time to make the code support for 2.6. Sincerely sorry :(
