### ISSUE TITLE
Installed with pip but not working

### ISSUE THREAD

**Issue by Tabrizian** [reorx/httpstat#7]
Hi there,
First thanks for your really awesome tool, my problem with this is that I installed it with ```pip``` on ubuntu but my problem is that although I it is installed in the ```~/.local/lib/python2.7/site-packages``` but it isn't available via commandline. I mean when I type ```httpstat``` it says  ```command not found```.

**Comment by reorx** [comment]
Maybe this is because you have customized your Python installation path,
check if there's a bin/ under your ~/.local/ , and see if httpstat is
there. Pip follows Python's internal mechanism and will put command into
where Python's bin folder lies.
Iman Tabrizian <notifications@github.com>于2016年9月23日 周五下午9:07写道：

**Comment by Tabrizian** [comment]
HttpStat is there and also it is in the bin folder

**Comment by reorx** [comment]
If so, you just need to add ~/.local/bin to PATH, therefore all the cli
programs installed by pip will be accessible.

Iman Tabrizian <notifications@github.com>于2016年9月27日 周二上午1:47写道：

**Comment by Tabrizian** [comment]
Thanks it's fixed now.
